# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
cache_path = "./.tmp/foundry/cache"
libs = ["./src/libs"]
src = "./src/contracts"
out = "./.build"
fs_permissions = [{ access = "read", path = "./.build"}]
