services:
  remixd:
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-slim
        WORKDIR /usr/app
        RUN apt-get update \
         && apt-get install -y bash

        # Install remixd (sharing files from host to remix editor)
        RUN npm install -g @remix-project/remixd \
         && sed -i s/127.0.0.1/0.0.0.0/g /usr/local/lib/node_modules/@remix-project/remixd/src/websocket.js

    entrypoint: /bin/bash -lc
    ports:
      - "65520:65520"
      - "65523:65523"
      - "65525:65525"
    volumes:
      - ../../src/:/usr/app/src
    command: |
      'remixd -s /usr/app/src --remix-ide http://localhost:8001/'

  remix:
    image: remixproject/remix-ide:remix_live
    ports:
      - "8001:80"

  anvil:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bookworm-slim
        WORKDIR /usr/app
        RUN apt-get update \
         && apt-get install -y curl git

        # Install foundry
        RUN curl -L https://foundry.paradigm.xyz | bash \
         && export PATH="$PATH:/root/.foundry/bin" \
         && foundryup

    entrypoint: /bin/bash -lc
    ports:
      - "8545:8545"
    volumes:
      - ../../:/usr/app
    command: |
      '
      echo -e "\n!!\n!! Anvil state will be saved/loaded from .tmp/anvil/state.json\n!!\n" ; \
      anvil -p 8545 --host "0.0.0.0" --allow-origin "*" --mnemonic "test test test test test test test test test test test junk" $([ -f "/usr/app/.tmp/anvil/state.json" ] && echo "--load-state /usr/app/.tmp/anvil/state.json") --dump-state /usr/app/.tmp/anvil/state.json
      '

  shell:
    profiles: ["utils"]
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-slim
        WORKDIR /usr/app
        RUN apt-get update \
         && apt-get install -y curl git

        # Install foundry
        RUN curl -L https://foundry.paradigm.xyz | bash \
         && export PATH="$PATH:/root/.foundry/bin" \
         && foundryup

    entrypoint: /bin/bash -lc
    volumes:
      - dev-env-node-modules:/usr/app/node_modules
      - ../../:/usr/app
    environment:
      ETH_RPC_URL: http://host.docker.internal:8545
