services:
  shell:
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-slim
        WORKDIR /usr/app/
        RUN apt-get update \
         && apt-get install -y curl git bash \
         && apt-get clean \
         && git config --global --add safe.directory /usr/app

        # Install foundry
        RUN curl -L https://foundry.paradigm.xyz | bash \
         && export PATH="$PATH:/root/.foundry/bin" \
         && foundryup

    entrypoint: /bin/bash -lc

    environment:
      CI: ${CI}
      ETH_RPC_URL: "http://anvil:8545"

    volumes:
      - ../../:/usr/app
      - easyntropy-contracts-node-modules:/usr/app/node_modules

  anvil:
    image: ghcr.io/foundry-rs/foundry:stable
    ports:
      - "8545:8545"
    volumes:
      - ../../:/usr/app
    entrypoint:
      - "anvil"
      - "--chain-id"
      - "1337"
      - "--port"
      - "8545"
      - "--host"
      - "0.0.0.0"
      - "--allow-origin"
      - "*"
      # - "--load-state"
      # - "/usr/app/eth/anvil/state.json"
      # - '--dump-state'
      # - '/usr/app/eth/anvil/state.json'

volumes:
  easyntropy-contracts-node-modules:
